version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/jsonv"
    schedule:
      interval: "weekly"
updates:
  - package-ecosystem: "nuget"
    directory: "/tests/jsonv.Tests"
    schedule:
      interval: "weekly"      
