version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/jsonv"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/test/jsonv.Tests"
    schedule:
      interval: "weekly"
